batis_crowdsourcing_homepage:
    path:     /
    defaults: { _controller: BatisCrowdsourcingBundle:Project:index }

batis_crowdsourcing_view:
    path:     /
    defaults: { _controller: BatisCrowdsourcingBundle:Project:index }