batis_core:
    resource: "@BatisCoreBundle/Resources/config/routing.yml"
    prefix:   /

batis_crowdsourcing:
    resource: "@BatisCrowdsourcingBundle/Resources/config/routing.yml"
    prefix:   /crowdsourcing/
