<?php

namespace Batis\CrowdsourcingBundle\Repository;

/**
 * WorksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorksRepository extends \Doctrine\ORM\EntityRepository
{
}
